name: myapp
description: Descripción de tu proyecto

# Especifica la versión de Flutter y Dart
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  firebase_auth: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0