name: myapp
description: Descripción de tu proyecto

# Especifica la versión de Flutter y Dart
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.16.0
  flutter_riverpod: 2.4.9
  freezed_annotation: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.4.8
  freezed: 2.4.5
  json_serializable: 6.7.1